apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fragtale.fullname" . }}
  labels:
    {{- include "fragtale.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "fragtale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 16 | quote }}
        kubectl.kubernetes.io/default-container: "{{ .Chart.Name }}"
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fragtale.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "fragtale.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        # Local NTP server side-car container.
        {{- if .Values.ntp.enabled }}
        - name: {{ .Chart.Name }}-chrony
          securityContext:
            capabilities:
              drop:
              # Do not allow chrony to modify the system time (it shouldn't even try')
              # See https://man7.org/linux/man-pages/man7/capabilities.7.html
              - SYS_TIME
            readOnlyRootFilesystem: true
          image: "{{ .Values.ntp.image.repository }}:{{ .Values.ntp.image.tag }}"
          imagePullPolicy: {{ .Values.ntp.image.pullPolicy }}
          ports:
            - name: tsp
              containerPort: 123
              protocol: UDP
          env:
          - name: NTP_SERVERS
            value: "{{ .Values.ntp.config.servers }}"
          - name: ENABLE_NTS
            value: "{{ .Values.ntp.config.nts }}"
          - name: NOCLIENTLOG
            value: "true"
          volumeMounts:
          - mountPath: /etc/chrony
            name: tmpfs-etc-chrony
          - mountPath: /run/chrony
            name: tmpfs-run-chrony
          - mountPath: /var/lib/chrony
            name: tmpfs-var-lib-chrony
        {{- end }}
        # App
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.startupProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
          - name: LOG_LEVEL
            {{- if .Values.app.debug }}
            value: "DEBUG"
            {{- else }}
            value: "INFO"
            {{- end }}
            {{- if .Values.app.backend.cassandra }}
          - name: FRAGTALE_API_PORT
            value: "{{ .Values.service.port }}"
          - name: FRAGTALE_API_AUDIENCE
            value: {{ print (include "fragtale.fullname" .) "." .Release.Namespace ".svc"}}
          - name: FRAGTALE_BACKEND_IMPLEMENTATION
            value: "cassandra"
          - name: FRAGTALE_BACKEND_NAMESPACE
            value: "{{ .Values.app.backend.cassandra.keyspace }}"
          - name: FRAGTALE_BACKEND_ENDPOINTS
            value: "{{ join "," .Values.app.backend.cassandra.hosts }}"
          - name: FRAGTALE_BACKEND_USERNAME
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.backend.cassandra.credentials }}
                key: username
          - name: FRAGTALE_BACKEND_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.backend.cassandra.credentials }}
                key: password
          - name: FRAGTALE_BACKEND_REPLFACTOR
            value: "{{ .Values.app.backend.cassandra.replicationFactor }}"
          {{- end }}
          {{- if .Values.ntp.enabled }}
          - name: FRAGTALE_INTEGRITY_NTPHOST
            value: "127.0.0.1:123"
          - name: FRAGTALE_INTEGRITY_TOLERANCE
            value: "{{ .Values.app.integrity.tolerance }}"
          {{- end }}
          # The metrics implementation has fairly low overhead and is enabled
          # by default.
          - name: FRAGTALE_METRICS_ENABLED
            value: "{{ ne (.Values.app.metrics).enabled false }}"
          volumeMounts:
          - mountPath: /var/run/secrets/tokens
            name: service-account-token
          - name: integrity-secret
            mountPath: "/secrets"
            readOnly: true
          {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
      # Service account for in-container CLI access.
      - name: service-account-token
        projected:
          sources:
          - serviceAccountToken:
              path: service-account
              expirationSeconds: 7200
              audience: {{ print (include "fragtale.fullname" .) "." .Release.Namespace ".svc"}}
      - name: integrity-secret
        secret:
          secretName: {{ include "fragtale.fullname" . }}-integrity
          items:
          - key: current_oid
            path: current_oid
          - key: current
            path: current
          - key: current_ts
            path: current_ts
          - key: previous_oid
            path: previous_oid
          - key: previous
            path: previous
          - key: correlation_oid
            path: correlation_oid
          - key: correlation
            path: correlation
      {{- if .Values.ntp.enabled }}
      - name: tmpfs-etc-chrony
        emptyDir:
          medium: Memory
          sizeLimit: 1Mi
      - name: tmpfs-run-chrony
        emptyDir:
          medium: Memory
          sizeLimit: 1Mi
      - name: tmpfs-var-lib-chrony
        emptyDir:
          medium: Memory
          sizeLimit: 1Mi
      - name: tmpfs-the-ground-up
        emptyDir:
          medium: Memory
          sizeLimit: 256Mi
    {{- end }}
      {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
