# https://raw.githubusercontent.com/k8ssandra/k8ssandra-operator/refs/heads/main/charts/k8ssandra-operator/crds/k8ssandra-operator-crds.yaml
apiVersion: k8ssandra.io/v1alpha1
kind: K8ssandraCluster
metadata:
  name: {{ include "fragtale-k8cs.fullname" . }}
spec:
  cassandra:
    # https://github.com/k8ssandra/management-api-for-apache-cassandra#supported-image-matrix
    serverVersion: {{ .Values.serverVersion }}
    # Allow nodes to be schedules on a single node k8s
    softPodAntiAffinity: true
    # Resource spec is required with softPodAntiAffinity is set to true
    resources:
      requests:
        cpu: {{ .Values.resources.cpu }}
        memory: {{ .Values.resources.memory }}
      limits:
        cpu: {{ .Values.resources.cpu }}
        memory: {{ .Values.resources.memory }}
    datacenters:
      - metadata:
          name: dc1
        size: {{ .Values.size }}
        #size: 1
        storageConfig:
          cassandraDataVolumeClaimSpec:
            {{- if .Values.resources.storageClassName }}
            storageClassName:  {{ .Values.resources.storageClassName }}
            {{- end }}
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: {{ .Values.resources.storage }}
        config:
          jvmOptions:
            heapSize: {{ .Values.resources.heapSize }}
