{
 "title": "Fragtale",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Fragtail CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"fragtale-dev\", container=\"fragtale\"}[90s])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Fragtail mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_working_set_bytes{namespace=\"fragtale-dev\", container=\"fragtale\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Published events to alive Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "fragtale_mb_published_events_count{topic!~\"\"}",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Publish to consumer delivery latency max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fragtale_mb_delivery_latency_max_micros{topic!~\"\"}",
     "legendFormat": "{{topic}}  {{pod}}"
    }
   ]
  },
  {
   "title": "Correlated wait max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "fragtale_mb_correlated_wait_max_micros{topic!~\"\"}",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Delivered events by alive Pods",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "fragtale_mb_delivered_events_count{topic!~\"\"}",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Publish to consumer delivery latency avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fragtale_mb_delivery_latency_avg_millis{topic!~\"\"}",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Correlated wait avg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "fragtale_mb_correlated_wait_avg_millis{topic!~\"\"}",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Publish rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(fragtale_mb_published_events_count{topic!~\"\"}[2m])",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Published data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(fragtale_mb_published_bytes_count{topic!~\"\"}[5m])",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Delivery rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "rate(fragtale_mb_delivered_events_count{topic!~\"\"}[2m])",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  },
  {
   "title": "Delivered data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(fragtale_mb_delivered_bytes_count{topic!~\"\"}[5m])",
     "legendFormat": "{{topic}} {{pod}}"
    }
   ]
  }
 ]
}